# manifests/blocker-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: blocker
spec:
  tolerations:
    - key: "accelerator"
      operator: "Equal"
      value: "nvidia"
      effect: "NoSchedule"
  containers:
    - name: stress
      image: nvidia/cuda:11.0-base
      command: ["/bin/sh"]
      args: ["-c", "sleep 30"]
      resources:
        limits:
          nvidia.com/gpu: 1
  restartPolicy: Never
