apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: gang-tf-job
spec:
  minAvailable: 2
  schedulerName: volcano
  queue: ml-queue
  policies:
    - event: PodEvicted
      action: RestartJob
  tasks:
    - replicas: 2
      name: trainer
      template:
        spec:
          tolerations:
            - key: "accelerator"
              operator: "Equal"
              value: "nvidia"
              effect: "NoSchedule"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: accelerator
                    operator: In
                    values: ["nvidia"]
          containers:
            - name: trainer
              image: akash202k/tf-volcano-demo:v1
              resources:
                requests:
                  cpu: "2"
                  memory: "4Gi"
                  nvidia.com/gpu: 1
                limits:
                  cpu: "2"
                  memory: "4Gi"
                  nvidia.com/gpu: 1
          restartPolicy: Never